### ISSUE TITLE
【3.10.21】前端单独编译报错

### ISSUE THREAD

**Issue by Miguitian** [TencentBlueKing/bk-cmdb#7074]
问题描述
===========
按照编译手册进行单独的前端编译，执行make ui。但是最后编译报错。

重现方法
================
安装nodejs，node版本v14.21.3。npm版本：6.14.18。cmdb版本：v3.10.21 进行编译时报错 报错信息为：
  build [====================] 100% (41.4 seconds)

Build completed in 1.876s

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
     ╷
1378 │       background-color: $ghostBackgroundColor !important;
     │                         ^^^^^^^^^^^^^^^^^^^^^
     ╵
  src/components/model-manage/field-group/index.vue 1378:25  root stylesheet
    at processResult (/Users/gtm/go/src/configcenter/src/ui/node_modules/webpack/lib/NormalModule.js:764:19)
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/webpack/lib/NormalModule.js:866:5
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/Users/gtm/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:104488:16)
    at render_closure.call$0 (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:89055:23)
    at Object.Primitives_applyFunction (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:1152:30)
    at Object.Function_apply (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:5288:16)
    at _callDartFunctionFast (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:7139:16)
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:7117:18
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
     ╷
1760 │               left: -$marginLeft;
     │                      ^^^^^^^^^^^
     ╵
  src/views/global-config/children/module-builder.vue 1760:22  root stylesheet
    at processResult (/Users/gtm/go/src/configcenter/src/ui/node_modules/webpack/lib/NormalModule.js:764:19)
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/webpack/lib/NormalModule.js:866:5
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/Users/gtm/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:104488:16)
    at render_closure.call$0 (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:89055:23)
    at Object.Primitives_applyFunction (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:1152:30)
    at Object.Function_apply (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:5288:16)
    at _callDartFunctionFast (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:7139:16)
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:7117:18
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
     ╷
1353 │                 border-top: 8px solid $customizeColor;
     │                                       ^^^^^^^^^^^^^^^
     ╵
  src/views/model-manage/children/model-details/index.vue 1353:39  root stylesheet
    at processResult (/Users/gtm/go/src/configcenter/src/ui/node_modules/webpack/lib/NormalModule.js:764:19)
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/webpack/lib/NormalModule.js:866:5
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/Users/gtm/go/src/configcenter/src/ui/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:104488:16)
    at render_closure.call$0 (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:89055:23)
    at Object.Primitives_applyFunction (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:1152:30)
    at Object.Function_apply (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:5288:16)
    at _callDartFunctionFast (/Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:7139:16)
    at /Users/gtm/go/src/configcenter/src/ui/node_modules/sass/sass.dart.js:7117:18

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 <!-- 示例： ./cmdb/cmdb-apiserver --version 输出的内容:
Version  : 3.10.21
Tag      : 
Branch   : v3.10.21

**Comment by yangyy** [comment]
请使用v3.10.21以上的版本或参考 #6993 修复

**Comment by Miguitian** [comment]
thx
