### ISSUE TITLE
cmdb_webserver经常挂掉

### ISSUE THREAD

**Issue by haijingtang** [TencentBlueKing/bk-cmdb#7175]
问题描述
===========
通过./start.sh启动所有服务后，页面能够正常访问。但只要点击“业务”、“资源”、“模型”等标签2-3次后，cmdb_webserver进程就不存在了。但其他服务都进程都正常。查看cmdb_webserver的日志有以下异常：
panic: interface conversion: *restful.Response is not http.Flusher: missing method Flush

goroutine 96 [running]:
configcenter/vendor/github.com/gin-gonic/gin.(*responseWriter).Flush(0x100010000?)
        /Users/xxxx/go-workspace/src/configcenter/vendor/github.com/gin-gonic/gin/response_writer.go:113 +0x30
net/http/httputil.(*maxLatencyWriter).delayedFlush(0x14000245fb0)
        /usr/local/go/src/net/http/httputil/reverseproxy.go:711 +0xd4
created by time.goFunc
        /usr/local/go/src/time/sleep.go:176 +0x38

请协助解决。谢谢。

重现方法
================
每次启动后，该问题必现。

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [x] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by haijingtang** [comment]
bk-cmdb版本3.7.x

**Comment by haijingtang** [comment]
go 升级到1.17.13，已解决。最初用的1.20.x版本竟然也不行。
