### ISSUE TITLE
3.13.3前端编译失败

### ISSUE THREAD

**Issue by zhuwei432** [TencentBlueKing/bk-cmdb#8259]
bk-cmdb-ui@1.0.0 build
> node builder/build.js BUILD_OUTPUT=/opt/bk-cmdb-release-v3.13.3/src/bin/build/

internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module 'http-proxy-middleware'
Require stack:
- /opt/bk-cmdb-release-v3.13.3/src/ui/builder/config/index.js
- /opt/bk-cmdb-release-v3.13.3/src/ui/builder/webpack/index.js
- /opt/bk-cmdb-release-v3.13.3/src/ui/builder/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/opt/bk-cmdb-release-v3.13.3/src/ui/builder/config/index.js:16:28)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/bk-cmdb-release-v3.13.3/src/ui/builder/config/index.js',
    '/opt/bk-cmdb-release-v3.13.3/src/ui/builder/webpack/index.js',
    '/opt/bk-cmdb-release-v3.13.3/src/ui/builder/build.js'
  ]
}
make: *** [ui] Error 1

**Comment by yangyy** [comment]
请参考 #7873 解决
